### ISSUE TITLE
Making New Logo for the app

### ISSUE THREAD

**Issue by Bhavye-Malhotra** [budhirajamadhav/LitMemes#3]
Hey, the original logo seems kind of unprofessional and kind of not appealing.
I am working on something if you might like it. 🙂

**Comment by Bhavye-Malhotra** [comment]
![Logo](https://i.imgur.com/4XJBaEa.gif)

**Comment by BudhirajaMadhav** [comment]
Ok great, I'm assigning this issue to you!
